### ISSUE TITLE
Bug: ci/cd pipeline example and docs, add `passed` marker for image creation job

### ISSUE THREAD

**Issue by siredmar** [elbb/bb-buildingblock#20]
There is a bug in the example ci/cd pipeline and docs that doesn't allow proper triggering of the docker image build step after gitversion has been completed.

Before: 
```
- name: Create docker images for ((bb_name)) and push them
    public: true
    plan:
      - in_parallel:
          - get: source
          - get: s3-gitversion
            trigger: true
            params:
              unpack: true
```

Aftre bugfix:
```
- name: Create docker images for ((bb_name)) and push them
    public: true
    plan:
      - in_parallel:
          - get: source
          - get: s3-gitversion
            passed: [Generate gitversion and put it on S3]
            trigger: true
            params:
              unpack: true
```
